---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "lazyca.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "lazyca.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: {{ default (include "lazyca.name" .) .Values.certificate.commonName }}
  secretName: {{ include "lazyca.ca-certificate.secretName" . }}
  privateKey:
    algorithm: {{ .Values.certificate.privateKey.algorithm }}
    size: {{ .Values.certificate.privateKey.size }}
  issuerRef:
    name: {{ include "lazyca.fullname" . }}-selfsigned
    kind: Issuer
    group: cert-manager.io
  {{- if .Values.certificate.duration }}
  duration: {{ .Values.certificate.duration }}
  {{- end -}}
  {{- if .Values.certificate.renewBefore }}
  renewBefore: {{ .Values.certificate.renewBefore }}
  {{- end -}}
  {{- if (or .Values.certificate.secretTemplate.annotations .Values.certificate.secretTemplate.labels) }}
  secretTemplate:
    {{- if .Values.certificate.secretTemplate.annotations }}
    annotations: {{ toYaml .Values.certificate.secretTemplate.annotations | nindent 6 }}
    {{- end -}}
    {{- if .Values.certificate.secretTemplate.labels }}
    labels: {{ toYaml .Values.certificate.secretTemplate.labels | nindent 6 }}
    {{- end -}}
  {{- end -}}
