---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-selfsigned" (include "lazyca.fullname" .) | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "lazyca.labels" . | nindent 4 }}
spec:
  selfSigned: {}
