{{- if and .Values.tls.enabled .Values.tls.generateOwnerCert -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-%s-%s-client" .Release.Name .Values.database.name .Values.database.owner | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "lazycnpgcluster.labels" . | nindent 4 }}
spec:
  secretName: {{ printf "%s-%s-%s-client-certificate" .Release.Name .Values.database.name .Values.database.owner | quote }}
  usages:
  - "client auth"
  commonName: {{ .Values.database.owner | quote }}
  privateKey:
    algorithm: "ECDSA"
    size: 256
  issuerRef:
    {{- with .Values.tls.clientCA }}
    name: {{ .issuer.name | quote }}
    kind: {{ .issuer.kind | quote }}
    group: {{ .issuer.group | quote }}
    {{- end }}
  secretTemplate:
    labels:
      cnpg.io/reload: ""
      {{- include "lazycnpgcluster.labels" . | nindent 6 }}
{{- end -}}
