
nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/doubleu-labs/coredns
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

deployment:
  name: ""
  annotations: {}
  replicaCount: 1
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 25%
  topologySpreadConstraints: []
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
      ephemeral-storage: 2Gi
    requests:
      cpu: 300m
      memory: 512Mi
      ephemeral-storage: 1Gi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1
  affinity: {}
  tolerations: {}
  nodeSelector: {}
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
      - ALL
      add:
      - NET_BIND_SERVICE

service:
  type: ClusterIP
  name: ""
  annotations: {}
  clusterIP: ""
  clusterIPs: []
  externalIPs: []
  externalTrafficPolicy: ""
  ipFamilyPolicy: ""
  clusterDomain: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

################################################################################

servers:
- plugins:
  - name: health
  - name: ready
  - name: errors
  - name: forward
    parameters: . 8.8.8.8 8.8.4.4
  - name: cache
    parameters: 30s

snippets: []

zoneFiles: []

extraVolumes: []

extraVolumeMounts: []

extraSecrets: []

certificate:
  existing:
    enabled: false
    secretName: dns-tls
  certManager:
    enabled: false
    commonName: ""
    subjectAltNames:
      dns: []
      ipAddress: []
    issuer:
      group: cert-manager.io
      kind: Issuer
      name: dns
    duration: 672h
    renewBefore: 48h
    revisionHistoryLimit: 1
