---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.objectName" (list . "headless") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-valkey
      port: 6379
      targetPort: valkey
      protocol: TCP
    {{- if eq .Values.architecture "cluster" }}
    - name: gossip
      port: 16379
      targetPort: gossip
    {{- end }}
    {{- if and (eq .Values.architecture "replica") .Values.replica.sentinel.enabled }}
    - name: sentinel
      port: 26379
      targetPort: sentinel
      protocol: TCP
    {{- end }}
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}
