{{- if eq .Values.architecture "cluster" -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "valkey.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - pods
{{- end -}}
