---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "dns.labels" . | nindent 4 }}
data:
  Corefile: |
    {{- range .Values.snippets }}
    ({{ .name }}) {
      {{- range .plugins }}
        {{ .name }}{{ if .parameters }} {{ .parameters }}{{ end }}{{ if .configBlock }} { {{ .configBlock | nindent 12 }}
        }{{ end }}
      {{- end }}
    }
    {{- end }}
    {{ range .Values.servers }}
    {{- if not .zones }}.{{ end }}{{- range $idx, $zone := .zones }}{{ if $idx }} {{ else }}{{ end }}{{ default "" $zone.scheme }}{{ default "." $zone.zone }}{{ if $zone.port }}:{{ $zone.port }}{{ end }}{{ end }} {
      {{- range .plugins }}
        {{ .name }}{{ if .parameters }} {{ .parameters }}{{ end }}{{ if .configBlock }} { {{ .configBlock | nindent 12 }}
        }{{ end }}
      {{- end }}
    }
    {{ end }}
{{- if .Values.zoneFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dns.fullname" . }}-zones
  namespace: {{ .Release.Namespace }}
  labels: {{- include "dns.labels" . | nindent 4 }}
data:
  {{- range .Values.zoneFiles }}
  {{ .filename }}: {{- toYaml .contents | indent 2 -}}
  {{ end }}
{{- end }}