{{- if and
  (eq .Values.architecture "replica")
  (ge (int .Values.replica.replicas) 1)
-}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valkey.objectName" (list . "replica") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
data:
  valkey.conf: |-
    {{- include "valkey.config.common" . | nindent 4 }}
    {{- include "valkey.config.common.tls" (list . .Values.tls.existingSecret.replica "6379") | nindent 4 }}
    {{- if .Values.auth.enabled }}
    aclfile /etc/valkey/auth.acl
    include /run/secrets/valkey/config/replica.conf
    {{- end }}
    {{- if or
      .Values.tls.certManager.enabled
      (and .Values.tls.certManager.enabled .Values.tls.certManager.csiDriver)
      .Values.tls.existingSecret.replica
    }}
    tls-replication yes
    {{- end }}
    replicaof {{ printf "%s-primary-0.%s-headless.%s.svc.%s 6379" (include "valkey.fullname" .) (include "valkey.fullname" .) .Release.Namespace .Values.service.clusterDomain }}
    replica-announce-port 6379
{{- end -}}
