{{- if and
  (eq .Values.architecture "replica")
  (ge (int .Values.replica.replicas) 1)
  .Values.auth.enabled
-}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.objectName" (list . "replica-conf") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
data:
  replica.conf: {{ include "valkey.replica.secret.conf" . | b64enc }}
{{- end -}}
