---
name: Release Charts
on:
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: azure/setup-helm@v4
    - run: |
        mkdir dist
        for chart in $(ls -d charts/*/); do
          helm package $chart --destination dist
        done
        helm repo index --url https://labs.doubleu.codes/charts dist
    - uses: wranders/markdown-to-pages-action@v1
      with:
        token: ${{ github.token }}
        out_path_not_empty: true
        files: |
          README.md
          ./charts/dns/README.md
    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist
  deploy:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment
